### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by lukemesiti** [juniordevio/splashpage#30]
at the moment the sign up form allows you to submit even if the two select boxes are empty. This can cause gaps in our data. Change it so this can't happen.

This might help. https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation

**Comment by nguyenhoamy1602** [comment]
Working on this!

**Comment by nguyenhoamy1602** [comment]
I fixed the "Sign-Up" button, aren't advanced enough to write alert yet, and because the button is not enabled, so there is no way for alert to appear anyway. Just a side question, are there only a few gaps in the data because I'm not sure if the values are being sent correctly to Mailchimp? The code looks a bit weird to me :P
